feat: add and update aliases

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -31,8 +31,6 @@ setopt EXTENDED_HISTORY
 
 export PATH="/home/gcg/.gem/ruby/2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
 export PATH="$PATH:./node_modules/.bin:../node_modules/.bin:../../node_modules/.bin:../../../node_modules/.bin:../../../../node_modules/.bin"
-# golang
-export PATH="$PATH:/home/gcg/go/bin"
 # pip
 export PATH="$PATH:/home/gcg/.local/bin"
 # parasite (proxy to record and replay requests)
@@ -71,7 +69,15 @@ alias gc='git commit --gpg-sign -v'
 alias gcam='git commit --gpg-sign -a -m'
 alias gst='git status'
 alias griom='git fetch origin &&git rebase -i origin/master || git rebase -i origin/main'
-alias grom='git fetch origin && git rebase origin/master || git rebase origin/main'
+alias grom='git fetch origin && git rebase origin/master 2>/dev/null || git rebase origin/main'
+gsom() {
+  git fetch origin
+  BASE=$(git merge-base origin/master $(git rev-parse --abbrev-ref HEAD))
+  if ([[ -z "$BASE" ]]) then
+    BASE=$(git merge-base origin/main $(git rev-parse --abbrev-ref HEAD))
+  fi
+  git reset "$BASE"
+}
 alias griod='git fetch &&git rebase -i origin/develop'
 alias gd='git diff --minimal'
 alias gdc='git diff --cached'
@@ -96,8 +102,8 @@ alias nn='f -e nvim'
 alias nd='node -r ~/dotfiles/node'
 alias nt='nvim /tmp/$RANDOM'
 alias ntsx='nvim /tmp/$RANDOM.tsx'
-na  () { nvim "+/\c$*" `ag --ignore yarn.lock --ignore-dir node_modules --ignore-dir .next -l "$*"` }
-nf  () { nvim `find -name "$*" -not -path "./node_modules/*"` }
+na() { nvim "+/\c$*" `ag --ignore yarn.lock --ignore-dir node_modules --ignore-dir .next -l "$*"` }
+nf() { nvim `find -name "$*" -not -path "./node_modules/*"` }
 nlint() { nvim `eslint --cache -f ~/code/_archive/eslint-formatter-list .` }
 alias ff='ag -g'
 alias w='watch -n 0.5 --color'
@@ -135,7 +141,7 @@ alias gitconfig='nvim ~/.gitconfig'
 alias aa='ag --ignore yarn.lock --ignore node_modules --ignore package-lock.json --context=3'
 nrc() {
   cd ~/dotfiles/
-  n awesome/rc.lua
+  $EDITOR awesome/rc.lua
   cd -
   # echo 'awesome.restart()' | awesome-client
 }
@@ -366,30 +372,19 @@ alias sdr='sudo systemctl daemon-reload'
 alias sstart='sudo systemctl start'
 alias blue='bluetoothctl'
 function jbl {
-  blue power on
-  blue connect 04:FE:A1:B3:FF:47 
+  bluetoothctl power on
+  bluetoothctl connect 04:FE:A1:B3:FF:47 
 }
 function ed { # Edifier
-  blue power on
-  while (! blue connect 04:FE:A1:E8:D9:20)
+  bluetoothctl power on
+  while (! bluetoothctl connect 04:FE:A1:E8:D9:20)
   do
     sleep 0.1
   done
-}
-function redmi { # Redmi earplug
-  blue power on
-  while (! blue connect 1C:52:16:76:54:DA)
-  do
-    sleep 0.1
-  done
-  # while (! blue connect 1C:52:16:76:59:78)
-  # do
-  #   sleep 0.1
-  # done
 }
 function btoff { # Edifier
-  blue disconnect 04:FE:A1:B3:FF:47 
-  blue disconnect 04:FE:A1:E8:D9:20
+  bluetoothctl disconnect 04:FE:A1:B3:FF:47 
+  bluetoothctl disconnect 04:FE:A1:E8:D9:20
 }
 alias blueswitch='~/dotfiles/scripts/blueswitch.sh'
 
@@ -445,19 +440,6 @@ function sleep_until {
   sleep $seconds
 }
 alias csv='column -s, -t | less -#2 -N -S'
-
-function goodnight() {
-  powersave
-  chromium http://homepages.neiu.edu/~mtailor/cs300/images/bluecolor.jpg
-  xset s off
-  echo "---"
-  echo "--- Don't forget to move your mouse to the bottom right edge of the screen to disable the lock"
-  echo "---"
-  date
-  sleep_until 06:30
-  xbacklight -set 100%
-  echo "--- Remember to do xset s"
-}
 
 alias win="/home/gcg/win/run.sh"
 alias mac="(cd /home/gcg/mac/ ; ./OpenCore-Boot.sh)"
@@ -560,7 +542,7 @@ alias df='df -h 2>/dev/null'
 alias tree='tree -I node_modules'
 alias groot='git rebase -i --root'
 alias ytdl='youtube-dl -x --audio-format mp3 --force-ipv4 -i'
-alias beep='aplay ~/dotfiles/sounds/beep-07.wav'
+alias beep='aplay ~/dotfiles/sounds/beep-07.wav >/dev/null 2>/dev/null'
 alias th='aiksaurus'
 alias uz='unzip'
 
@@ -744,15 +726,28 @@ function cloud() {
     echo "Usage: cloud file"
     return
   fi
+  confirm "Upload to Glacier with a minimum of 3 months?" || return 1
   echo "Encrypting and uploading file '${1}'"
   gpg --encrypt -r gunar@gunargessner.com <"${1}" \
-    | aws s3 cp - "s3://${AWS_S3_CLOUD_BACKUP_BUCKET}/${1}" --storage-class STANDARD_IA  \
+    | aws s3 cp - "s3://${AWS_S3_CLOUD_BACKUP_BUCKET}/${1}" --storage-class DEEP_ARCHIVE  \
     || exit 1
   echo "Done! You can safely remove '${1}'"
 }
 function cloud-and-delete() {
   source ~/cloud/.envrc
   cloud "$1" && rm -f "$1" && echo "Removed $1 successfully."
+}
+confirm() {
+    # call with a prompt string or use a default
+    read -r "response?${1:-Are you sure?} [y/N] "
+    case "$response" in
+        [yY][eE][sS]|[yY]) 
+            true
+            ;;
+        *)
+            false
+            ;;
+    esac
 }
 function cloud-ls() {
   source ~/cloud/.envrc
@@ -789,7 +784,7 @@ alias ink="inkscape"
 
 # alias ng='killall ngrok 2>/dev/null;ngrok http -subdomain=gunar 3000 >/dev/null &!'
 # alias ng='lt --subdomain gunar --port'
-function ng() {
+function ngrok() {
   # Creates a tunnel
   # dev.gunar.uk
   # dev.besloor.com
@@ -826,3 +821,30 @@ alias psql="pgcli"
 
 # If I ever get stuck on "command not found" again and decide I want to expand aliases inside function, I can uncomment this:
 # shopt expand_aliases
+#
+#
+function aws-abort-all-multipart() {
+  if [ $# -eq 0 ]
+  then
+    echo "Usage: aws-abort-all-multipart <bucket-name>"
+    return
+  fi
+  BUCKETNAME=$1
+
+  aws s3api list-multipart-uploads --bucket $BUCKETNAME \
+  | jq -r '.Uploads[] | "--key \"\(.Key)\" --upload-id \(.UploadId)"' \
+  | while read -r line; do
+     $(ws s3api abort-multipart-upload --bucket $BUCKETNAME $line);
+  done
+}
+alias host-static="surge"
+alias image-size="exiv2"
+function qrcode() {
+  zbarimg -q $* | cut -d':' -f2-
+}
+
+
+# v4l2-ctl --list-devices # Get the video devices for the camlink and dummy.
+ELGATO=/dev/video3
+V4LOOP=/dev/video4
+alias elgato="sudo modprobe v4l2loopback devices=1 exclusive_caps=1 && ffmpeg -f v4l2 -input_format yuyv422 -framerate 60 -video_size 1920x1080 -i $ELGATO -pix_fmt yuyv422 -codec copy -f v4l2 $V4LOOP"
